/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 101
#define LARGE_STATE_COUNT 23
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 14
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  sym__id = 1,
  anon_sym_LBRACK = 2,
  anon_sym_COMMA = 3,
  anon_sym_RBRACK = 4,
  anon_sym_SEMI = 5,
  anon_sym_assert = 6,
  anon_sym_COLON = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_tailstrict = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_EQ = 13,
  anon_sym_if = 14,
  anon_sym_then = 15,
  anon_sym_else = 16,
  anon_sym_function = 17,
  anon_sym_local = 18,
  sym_number = 19,
  aux_sym_quoted_string_token1 = 20,
  aux_sym_quoted_string_token2 = 21,
  aux_sym_quoted_string_token3 = 22,
  aux_sym_quoted_string_token4 = 23,
  sym_dollar = 24,
  sym_null = 25,
  sym_self = 26,
  sym_super = 27,
  sym_comment = 28,
  sym_text_block_start = 29,
  sym_text_block_line = 30,
  sym_text_block_end = 31,
  sym_document = 32,
  sym_expression = 33,
  sym_array = 34,
  sym_asserted_expression = 35,
  sym_assert = 36,
  sym_boolean = 37,
  sym_call = 38,
  sym_arguments = 39,
  sym_argument = 40,
  sym_conditional = 41,
  sym_function = 42,
  sym_params = 43,
  sym_param = 44,
  sym_local = 45,
  sym_binding = 46,
  sym_string = 47,
  sym_quoted_string = 48,
  sym_text_block = 49,
  sym_param_ref_id = 50,
  sym_var_id = 51,
  sym_var_ref_id = 52,
  aux_sym_array_repeat1 = 53,
  aux_sym_arguments_repeat1 = 54,
  aux_sym_params_repeat1 = 55,
  aux_sym_local_repeat1 = 56,
  aux_sym_text_block_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__id] = "_id",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_SEMI] = ";",
  [anon_sym_assert] = "assert",
  [anon_sym_COLON] = ":",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_tailstrict] = "tailstrict",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_function] = "function",
  [anon_sym_local] = "local",
  [sym_number] = "number",
  [aux_sym_quoted_string_token1] = "quoted_string_token1",
  [aux_sym_quoted_string_token2] = "quoted_string_token2",
  [aux_sym_quoted_string_token3] = "quoted_string_token3",
  [aux_sym_quoted_string_token4] = "quoted_string_token4",
  [sym_dollar] = "dollar",
  [sym_null] = "null",
  [sym_self] = "self",
  [sym_super] = "super",
  [sym_comment] = "comment",
  [sym_text_block_start] = "text_block_start",
  [sym_text_block_line] = "text_block_line",
  [sym_text_block_end] = "text_block_end",
  [sym_document] = "document",
  [sym_expression] = "expression",
  [sym_array] = "array",
  [sym_asserted_expression] = "asserted_expression",
  [sym_assert] = "assert",
  [sym_boolean] = "boolean",
  [sym_call] = "call",
  [sym_arguments] = "arguments",
  [sym_argument] = "argument",
  [sym_conditional] = "conditional",
  [sym_function] = "function",
  [sym_params] = "params",
  [sym_param] = "param",
  [sym_local] = "local",
  [sym_binding] = "binding",
  [sym_string] = "string",
  [sym_quoted_string] = "quoted_string",
  [sym_text_block] = "text_block",
  [sym_param_ref_id] = "param_ref_id",
  [sym_var_id] = "var_id",
  [sym_var_ref_id] = "var_ref_id",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_params_repeat1] = "params_repeat1",
  [aux_sym_local_repeat1] = "local_repeat1",
  [aux_sym_text_block_repeat1] = "text_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__id] = sym__id,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_assert] = anon_sym_assert,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_tailstrict] = anon_sym_tailstrict,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_local] = anon_sym_local,
  [sym_number] = sym_number,
  [aux_sym_quoted_string_token1] = aux_sym_quoted_string_token1,
  [aux_sym_quoted_string_token2] = aux_sym_quoted_string_token2,
  [aux_sym_quoted_string_token3] = aux_sym_quoted_string_token3,
  [aux_sym_quoted_string_token4] = aux_sym_quoted_string_token4,
  [sym_dollar] = sym_dollar,
  [sym_null] = sym_null,
  [sym_self] = sym_self,
  [sym_super] = sym_super,
  [sym_comment] = sym_comment,
  [sym_text_block_start] = sym_text_block_start,
  [sym_text_block_line] = sym_text_block_line,
  [sym_text_block_end] = sym_text_block_end,
  [sym_document] = sym_document,
  [sym_expression] = sym_expression,
  [sym_array] = sym_array,
  [sym_asserted_expression] = sym_asserted_expression,
  [sym_assert] = sym_assert,
  [sym_boolean] = sym_boolean,
  [sym_call] = sym_call,
  [sym_arguments] = sym_arguments,
  [sym_argument] = sym_argument,
  [sym_conditional] = sym_conditional,
  [sym_function] = sym_function,
  [sym_params] = sym_params,
  [sym_param] = sym_param,
  [sym_local] = sym_local,
  [sym_binding] = sym_binding,
  [sym_string] = sym_string,
  [sym_quoted_string] = sym_quoted_string,
  [sym_text_block] = sym_text_block,
  [sym_param_ref_id] = sym_param_ref_id,
  [sym_var_id] = sym_var_id,
  [sym_var_ref_id] = sym_var_ref_id,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_params_repeat1] = aux_sym_params_repeat1,
  [aux_sym_local_repeat1] = aux_sym_local_repeat1,
  [aux_sym_text_block_repeat1] = aux_sym_text_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__id] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tailstrict] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_quoted_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_string_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_dollar] = {
    .visible = true,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_self] = {
    .visible = true,
    .named = true,
  },
  [sym_super] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text_block_start] = {
    .visible = true,
    .named = true,
  },
  [sym_text_block_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text_block_end] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_asserted_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assert] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_params] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_local] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_text_block] = {
    .visible = true,
    .named = true,
  },
  [sym_param_ref_id] = {
    .visible = true,
    .named = true,
  },
  [sym_var_id] = {
    .visible = true,
    .named = true,
  },
  [sym_var_ref_id] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_params_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_local_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_text_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_bindings = 2,
  field_body = 3,
  field_callee = 4,
  field_condition = 5,
  field_consequence = 6,
  field_default = 7,
  field_function = 8,
  field_message = 9,
  field_param = 10,
  field_params = 11,
  field_value = 12,
  field_variable = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_bindings] = "bindings",
  [field_body] = "body",
  [field_callee] = "callee",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_default] = "default",
  [field_function] = "function",
  [field_message] = "message",
  [field_param] = "param",
  [field_params] = "params",
  [field_value] = "value",
  [field_variable] = "variable",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 1},
  [10] = {.index = 14, .length = 3},
  [11] = {.index = 17, .length = 3},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 1},
  [1] =
    {field_callee, 0},
  [2] =
    {field_body, 2},
    {field_params, 1},
  [4] =
    {field_value, 0},
  [5] =
    {field_condition, 1},
    {field_message, 3},
  [7] =
    {field_condition, 1},
    {field_consequence, 3},
  [9] =
    {field_bindings, 1},
    {field_body, 3},
  [11] =
    {field_value, 2},
    {field_variable, 0},
  [13] =
    {field_default, 2},
  [14] =
    {field_bindings, 1},
    {field_bindings, 2},
    {field_body, 4},
  [17] =
    {field_body, 3},
    {field_function, 0},
    {field_params, 1},
  [20] =
    {field_param, 0},
    {field_value, 2},
  [22] =
    {field_alternative, 5},
    {field_condition, 1},
    {field_consequence, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 54,
  [63] = 52,
  [64] = 57,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 80,
  [85] = 76,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 25,
  [95] = 23,
  [96] = 96,
  [97] = 26,
  [98] = 98,
  [99] = 24,
  [100] = 100,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_expression,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_expression] = {.index = 0, .length = 14},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_array,
    sym_asserted_expression,
    sym_boolean,
    sym_call,
    sym_conditional,
    sym_dollar,
    sym_function,
    sym_local,
    sym_null,
    sym_number,
    sym_self,
    sym_string,
    sym_super,
    sym_var_ref_id,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      ADVANCE_MAP(
        '"', 1,
        '#', 51,
        '$', 47,
        '\'', 4,
        '(', 32,
        ')', 33,
        ',', 28,
        '/', 6,
        '0', 35,
        ':', 31,
        ';', 30,
        '=', 34,
        '@', 2,
        '[', 27,
        ']', 29,
        '+', 10,
        '-', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(51);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(49);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(50);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '0') ADVANCE(36);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        'u', 24,
        '"', 1,
        '\'', 1,
        '/', 1,
        '\\', 1,
        'b', 1,
        'f', 1,
        'n', 1,
        'r', 1,
        't', 1,
      );
      END_STATE();
    case 12:
      ADVANCE_MAP(
        'u', 25,
        '"', 4,
        '\'', 4,
        '/', 4,
        '\\', 4,
        'b', 4,
        'f', 4,
        'n', 4,
        'r', 4,
        't', 4,
      );
      END_STATE();
    case 13:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(39);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(1);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(4);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      ADVANCE_MAP(
        '.', 38,
        'B', 14,
        'b', 14,
        'E', 13,
        'e', 13,
        'O', 15,
        'o', 15,
        'X', 19,
        'x', 19,
      );
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_quoted_string_token1);
      if (lookahead == '"') ADVANCE(43);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_quoted_string_token2);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_quoted_string_token3);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_quoted_string_token4);
      if (lookahead == '\'') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_dollar);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(9);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '*' &&
          lookahead != '/') ADVANCE(9);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'e', 2,
        'f', 3,
        'i', 4,
        'l', 5,
        'n', 6,
        's', 7,
        't', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'h') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'f') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_self);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_super);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_assert);
      END_STATE();
    case 50:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 55:
      if (lookahead == 'c') ADVANCE(56);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_tailstrict);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0, .external_lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0, .external_lex_state = 3},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0, .external_lex_state = 4},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__id] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_assert] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_tailstrict] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_quoted_string_token1] = ACTIONS(1),
    [aux_sym_quoted_string_token2] = ACTIONS(1),
    [aux_sym_quoted_string_token3] = ACTIONS(1),
    [aux_sym_quoted_string_token4] = ACTIONS(1),
    [sym_dollar] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_self] = ACTIONS(1),
    [sym_super] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(1),
    [sym_text_block_line] = ACTIONS(1),
    [sym_text_block_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(100),
    [sym_expression] = STATE(83),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(56),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_argument] = STATE(89),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_param_ref_id] = STATE(93),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(56),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_argument] = STATE(77),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_param_ref_id] = STATE(93),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(56),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_argument] = STATE(89),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_param_ref_id] = STATE(93),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(33),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(56),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_argument] = STATE(89),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_param_ref_id] = STATE(93),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(50),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(49),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(37),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(8)] = {
    [sym_expression] = STATE(50),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_RBRACK] = ACTIONS(39),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(9)] = {
    [sym_expression] = STATE(61),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(10)] = {
    [sym_expression] = STATE(66),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(11)] = {
    [sym_expression] = STATE(27),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(12)] = {
    [sym_expression] = STATE(53),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(13)] = {
    [sym_expression] = STATE(30),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(14)] = {
    [sym_expression] = STATE(70),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(15)] = {
    [sym_expression] = STATE(32),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(16)] = {
    [sym_expression] = STATE(34),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(17)] = {
    [sym_expression] = STATE(59),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(18)] = {
    [sym_expression] = STATE(58),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(19)] = {
    [sym_expression] = STATE(35),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(20)] = {
    [sym_expression] = STATE(60),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(21)] = {
    [sym_expression] = STATE(50),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
  [STATE(22)] = {
    [sym_expression] = STATE(37),
    [sym_array] = STATE(38),
    [sym_asserted_expression] = STATE(38),
    [sym_assert] = STATE(98),
    [sym_boolean] = STATE(38),
    [sym_call] = STATE(38),
    [sym_conditional] = STATE(38),
    [sym_function] = STATE(38),
    [sym_local] = STATE(38),
    [sym_string] = STATE(38),
    [sym_quoted_string] = STATE(46),
    [sym_text_block] = STATE(46),
    [sym_var_ref_id] = STATE(38),
    [sym__id] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_assert] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_function] = ACTIONS(15),
    [anon_sym_local] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [aux_sym_quoted_string_token1] = ACTIONS(21),
    [aux_sym_quoted_string_token2] = ACTIONS(21),
    [aux_sym_quoted_string_token3] = ACTIONS(21),
    [aux_sym_quoted_string_token4] = ACTIONS(21),
    [sym_dollar] = ACTIONS(19),
    [sym_null] = ACTIONS(23),
    [sym_self] = ACTIONS(23),
    [sym_super] = ACTIONS(23),
    [sym_comment] = ACTIONS(3),
    [sym_text_block_start] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 8,
      sym_text_block_start,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_quoted_string_token1,
      aux_sym_quoted_string_token2,
      aux_sym_quoted_string_token3,
      aux_sym_quoted_string_token4,
      sym_dollar,
    ACTIONS(41), 10,
      anon_sym_assert,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
      anon_sym_function,
      anon_sym_local,
      sym_null,
      sym_self,
      sym_super,
      sym__id,
  [26] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 8,
      sym_text_block_start,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_quoted_string_token1,
      aux_sym_quoted_string_token2,
      aux_sym_quoted_string_token3,
      aux_sym_quoted_string_token4,
      sym_dollar,
    ACTIONS(45), 10,
      anon_sym_assert,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
      anon_sym_function,
      anon_sym_local,
      sym_null,
      sym_self,
      sym_super,
      sym__id,
  [52] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 8,
      sym_text_block_start,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_quoted_string_token1,
      aux_sym_quoted_string_token2,
      aux_sym_quoted_string_token3,
      aux_sym_quoted_string_token4,
      sym_dollar,
    ACTIONS(49), 10,
      anon_sym_assert,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
      anon_sym_function,
      anon_sym_local,
      sym_null,
      sym_self,
      sym_super,
      sym__id,
  [78] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 8,
      sym_text_block_start,
      anon_sym_LBRACK,
      sym_number,
      aux_sym_quoted_string_token1,
      aux_sym_quoted_string_token2,
      aux_sym_quoted_string_token3,
      aux_sym_quoted_string_token4,
      sym_dollar,
    ACTIONS(53), 10,
      anon_sym_assert,
      anon_sym_true,
      anon_sym_false,
      anon_sym_if,
      anon_sym_function,
      anon_sym_local,
      sym_null,
      sym_self,
      sym_super,
      sym__id,
  [104] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(57), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [124] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_tailstrict,
    ACTIONS(61), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [142] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_tailstrict,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [158] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(67), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [178] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_tailstrict,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [194] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_else,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_then,
  [216] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_tailstrict,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [232] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [252] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(79), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [272] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 10,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_tailstrict,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [288] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(83), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [338] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [353] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [368] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [398] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [443] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 9,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
  [473] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_COMMA,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
    STATE(28), 1,
      sym_arguments,
    STATE(71), 1,
      aux_sym_array_repeat1,
  [492] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(111), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [506] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 4,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_EQ,
  [516] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym_var_id,
    STATE(91), 1,
      sym_param,
  [532] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(119), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [546] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      sym_param,
    STATE(81), 1,
      sym_var_id,
  [562] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      anon_sym_EQ,
    ACTIONS(105), 3,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [574] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(125), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [588] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym_var_id,
    STATE(91), 1,
      sym_param,
  [604] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(129), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [618] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(131), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [632] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_arguments,
    ACTIONS(133), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [646] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 1,
      anon_sym_SEMI,
    ACTIONS(137), 1,
      anon_sym_COLON,
    STATE(28), 1,
      sym_arguments,
  [662] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym_var_id,
    STATE(84), 1,
      sym_param,
  [678] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym_var_id,
    STATE(91), 1,
      sym_param,
  [694] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      sym_var_id,
    STATE(91), 1,
      sym_param,
  [710] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    STATE(74), 1,
      sym_var_id,
    STATE(90), 1,
      sym_binding,
  [723] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      anon_sym_then,
    STATE(28), 1,
      sym_arguments,
  [736] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym_text_block_line,
    ACTIONS(150), 1,
      sym_text_block_end,
    STATE(67), 1,
      aux_sym_text_block_repeat1,
  [749] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_RPAREN,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_arguments_repeat1,
  [762] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_array_repeat1,
  [775] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      anon_sym_SEMI,
    STATE(28), 1,
      sym_arguments,
  [788] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_RBRACK,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_array_repeat1,
  [801] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(163), 1,
      anon_sym_SEMI,
    STATE(87), 1,
      aux_sym_local_repeat1,
  [814] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_params_repeat1,
  [827] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_LPAREN,
    ACTIONS(172), 1,
      anon_sym_EQ,
    STATE(96), 1,
      sym_params,
  [840] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_text_block_line,
    ACTIONS(176), 1,
      sym_text_block_end,
    STATE(67), 1,
      aux_sym_text_block_repeat1,
  [853] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_RPAREN,
    ACTIONS(178), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_params_repeat1,
  [866] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      aux_sym_arguments_repeat1,
  [879] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    STATE(72), 1,
      sym_binding,
    STATE(74), 1,
      sym_var_id,
  [892] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_arguments_repeat1,
  [905] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_params_repeat1,
  [918] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_EQ,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [929] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym__id,
    STATE(81), 1,
      sym_var_id,
    STATE(91), 1,
      sym_param,
  [942] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_arguments,
  [955] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_params_repeat1,
  [968] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_params_repeat1,
  [981] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_COMMA,
    ACTIONS(208), 1,
      anon_sym_SEMI,
    STATE(86), 1,
      aux_sym_local_repeat1,
  [994] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_SEMI,
    STATE(86), 1,
      aux_sym_local_repeat1,
  [1007] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_params,
  [1017] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [1033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1041] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      sym_text_block_line,
    STATE(75), 1,
      aux_sym_text_block_repeat1,
  [1051] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_EQ,
  [1058] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_EQ,
  [1065] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_EQ,
  [1072] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_EQ,
  [1079] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_EQ,
  [1086] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_SEMI,
  [1093] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 1,
      anon_sym_EQ,
  [1100] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(23)] = 0,
  [SMALL_STATE(24)] = 26,
  [SMALL_STATE(25)] = 52,
  [SMALL_STATE(26)] = 78,
  [SMALL_STATE(27)] = 104,
  [SMALL_STATE(28)] = 124,
  [SMALL_STATE(29)] = 142,
  [SMALL_STATE(30)] = 158,
  [SMALL_STATE(31)] = 178,
  [SMALL_STATE(32)] = 194,
  [SMALL_STATE(33)] = 216,
  [SMALL_STATE(34)] = 232,
  [SMALL_STATE(35)] = 252,
  [SMALL_STATE(36)] = 272,
  [SMALL_STATE(37)] = 288,
  [SMALL_STATE(38)] = 308,
  [SMALL_STATE(39)] = 323,
  [SMALL_STATE(40)] = 338,
  [SMALL_STATE(41)] = 353,
  [SMALL_STATE(42)] = 368,
  [SMALL_STATE(43)] = 383,
  [SMALL_STATE(44)] = 398,
  [SMALL_STATE(45)] = 413,
  [SMALL_STATE(46)] = 428,
  [SMALL_STATE(47)] = 443,
  [SMALL_STATE(48)] = 458,
  [SMALL_STATE(49)] = 473,
  [SMALL_STATE(50)] = 492,
  [SMALL_STATE(51)] = 506,
  [SMALL_STATE(52)] = 516,
  [SMALL_STATE(53)] = 532,
  [SMALL_STATE(54)] = 546,
  [SMALL_STATE(55)] = 562,
  [SMALL_STATE(56)] = 574,
  [SMALL_STATE(57)] = 588,
  [SMALL_STATE(58)] = 604,
  [SMALL_STATE(59)] = 618,
  [SMALL_STATE(60)] = 632,
  [SMALL_STATE(61)] = 646,
  [SMALL_STATE(62)] = 662,
  [SMALL_STATE(63)] = 678,
  [SMALL_STATE(64)] = 694,
  [SMALL_STATE(65)] = 710,
  [SMALL_STATE(66)] = 723,
  [SMALL_STATE(67)] = 736,
  [SMALL_STATE(68)] = 749,
  [SMALL_STATE(69)] = 762,
  [SMALL_STATE(70)] = 775,
  [SMALL_STATE(71)] = 788,
  [SMALL_STATE(72)] = 801,
  [SMALL_STATE(73)] = 814,
  [SMALL_STATE(74)] = 827,
  [SMALL_STATE(75)] = 840,
  [SMALL_STATE(76)] = 853,
  [SMALL_STATE(77)] = 866,
  [SMALL_STATE(78)] = 879,
  [SMALL_STATE(79)] = 892,
  [SMALL_STATE(80)] = 905,
  [SMALL_STATE(81)] = 918,
  [SMALL_STATE(82)] = 929,
  [SMALL_STATE(83)] = 942,
  [SMALL_STATE(84)] = 955,
  [SMALL_STATE(85)] = 968,
  [SMALL_STATE(86)] = 981,
  [SMALL_STATE(87)] = 994,
  [SMALL_STATE(88)] = 1007,
  [SMALL_STATE(89)] = 1017,
  [SMALL_STATE(90)] = 1025,
  [SMALL_STATE(91)] = 1033,
  [SMALL_STATE(92)] = 1041,
  [SMALL_STATE(93)] = 1051,
  [SMALL_STATE(94)] = 1058,
  [SMALL_STATE(95)] = 1065,
  [SMALL_STATE(96)] = 1072,
  [SMALL_STATE(97)] = 1079,
  [SMALL_STATE(98)] = 1086,
  [SMALL_STATE(99)] = 1093,
  [SMALL_STATE(100)] = 1100,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_params, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_params, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_params, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_params, 5, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params, 5, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3, 0, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asserted_expression, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 4, 0, 6),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local, 4, 0, 7),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_local, 5, 0, 10),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional, 6, 0, 13),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 2),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text_block, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_ref_id, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_id, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 3, 0, 8),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_ref_id, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 4),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3, 0, 9),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 4, 0, 11),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, 0, 12),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assert, 2, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_text_block_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_text_block_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assert, 4, 0, 5),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_params_repeat1, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_local_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [222] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_text_block_start = 0,
  ts_external_token_text_block_line = 1,
  ts_external_token_text_block_end = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_text_block_start] = sym_text_block_start,
  [ts_external_token_text_block_line] = sym_text_block_line,
  [ts_external_token_text_block_end] = sym_text_block_end,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_text_block_start] = true,
    [ts_external_token_text_block_line] = true,
    [ts_external_token_text_block_end] = true,
  },
  [2] = {
    [ts_external_token_text_block_start] = true,
  },
  [3] = {
    [ts_external_token_text_block_line] = true,
    [ts_external_token_text_block_end] = true,
  },
  [4] = {
    [ts_external_token_text_block_line] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_jsonnet_external_scanner_create(void);
void tree_sitter_jsonnet_external_scanner_destroy(void *);
bool tree_sitter_jsonnet_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_jsonnet_external_scanner_serialize(void *, char *);
void tree_sitter_jsonnet_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jsonnet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__id,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_jsonnet_external_scanner_create,
      tree_sitter_jsonnet_external_scanner_destroy,
      tree_sitter_jsonnet_external_scanner_scan,
      tree_sitter_jsonnet_external_scanner_serialize,
      tree_sitter_jsonnet_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "jsonnet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
